# 开发环境配置
server:
  # 服务端口
  port: 5000
# mongodb 数据库连接配置
spring:
  data:
    mongodb:
      database: acgs
      host: 127.0.0.1
      port: 27017
# acgs 自动构建配置
acgs:
  build:
    base-path: org.acgs.cms.moudle
  cms:
    token-secret: x88Wf0991079889x8796a0Ac68f9ecJJU17c5Vbe8beod7d8d3e695*4